# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aurelius Prochazka 
name: Aurelius Prochazka
email: aure@aure.com
location: Mill Valley, CA 
company: AudioKit
company_url: http://audiokit.io/
github_url: https://github.com/audiokit 
description: My home page
favicon: favicon.png # Image must be in assets/images
repository: audiokit/AudioKit
# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. 
url: http://aurelius.com/

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet: false
defaults: []

kramdown:
  input: GFM
  syntax_highlighter: syntax_highlighter_opts

# Collections
collections:
  music:
    output: true
  songs:
    output: true
    permalink: /artist/:path/ 


# Disque
disque: my_disque_settings 

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation 
navs:
  -
    href: /
    label: Home
  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /presentations
    label: Presentations

  -
    href: /music
    label: Music

  -
    href: /publications
    label: Publications 

  -
    href: /about
    label: About

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]